#
# The `docker-compose.yml` file specifies the basics required for spinning up
# the environment, but does not include host bound ports or volumes.
#
# Local development settings, such as ports and volumes go in
# `docker-compose.override.yml`.
#
# Run: `docker compose up`
#
version: '2'
services:

  etl:
    build: .
    environment:
      - ETL_MONGO_URL=${ETL_MONGO_URL}
      - ETL_MMJM_MYSQL_HOST=${ETL_MMJM_MYSQL_HOST}
      - ETL_MMJM_MYSQL_USER=${ETL_MMJM_MYSQL_USER}
      - ETL_MMJM_MYSQL_PASS=${ETL_MMJM_MYSQL_PASS}
      - ETL_MMJM_MYSQL_NAME=${ETL_MMJM_MYSQL_NAME}
